apiVersion: v2
name: pgadmin
description: Helm Chart for pgAdmin on Kubernetes
type: application
version: 1.0.0
appVersion: "9.12.0"
kubeVersion: ">=1.16.0-0"
keywords:
  - pgadmin
  - postgresql
  - database
  - admin
home: https://www.pgadmin.org/
icon: https://www.pgadmin.org/static/img/pgadmin4.png
sources:
  - https://gitlab.example.com/homelab/helm-charts/-/tree/main/charts/pgadmin
  - https://www.pgadmin.org/
maintainers:
  - name: maintainer
    email: maintainer@example.com
    url: https://gitlab.example.com/homelab/helm-charts
