{{- if .Values.persistence.enabled }}
{{- range $volumeName, $volumeConfig := .Values.persistence.volumes }}
{{- if $volumeConfig.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.pvcName" (dict "Release" $.Release "Chart" $.Chart "Values" $.Values "volumeName" $volumeName) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "freshrss.labels" $ | nindent 4 }}
spec:
  accessModes:
    {{- range $volumeConfig.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if $.Values.persistence.storageClass }}
  {{- if (eq "-" $.Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $.Values.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ $volumeConfig.size | quote }}
---
{{- end }}
{{- end }}
{{- end }}
