apiVersion: v1
kind: Service
metadata:
  name: {{ include "privatebin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "privatebin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "privatebin.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
