apiVersion: v2
name: privatebin
description: A Helm chart for PrivateBin on Kubernetes
type: application
version: 1.0.1
appVersion: "2.0.3"
kubeVersion: ">=1.19.0"
keywords:
  - privatebin
  - pastebin
  - security
  - encryption
home: https://privatebin.info/
sources:
  - https://gitlab.example.com/homelab/helm-charts/-/tree/main/charts/privatebin
  - https://github.com/PrivateBin/PrivateBin
maintainers:
  - name: maintainer
    email: maintainer@example.com
    url: https://gitlab.example.com/homelab/helm-charts
