{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflared.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: {{ .Values.metrics.port }}
      name: metrics
{{- end }}
